on: pull_request
name: Python Lint and Style
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/pycodestyle-action@0.1.3
